### ISSUE TITLE
next after fixing compile

### ISSUE THREAD

**Issue by r-cemper** [kunal0297/iris-c-trie#5]
#13 14.95 USER>
#13 14.95
#13 14.95     Set sc = $ZF(-3, "insert", value)
#13 14.95     ^
#13 14.95 <DYNAMIC LIBRARY LOAD>Insert+1^PrefixTrie.Lookup.1 */usr/irissys/mgr/user/insert: cannot open shared object file: No such file or directory
#13 14.95 USER 3d1>
#13 DONE 17.1s

**Comment by kunal0297** [comment]
made the changes please check now if any errors are there

**Comment by r-cemper** [comment]
compile is ok but $ZF(-3)  seems to work different in IRIS 2025.1
---------------------------
USER>s lib="libfastlookup.so"

USER>s sc=$ZF(-3,lib)

S sc=$ZF(-3,lib)
^
<DYNAMIC LIBRARY LOAD> *Symbol GetZFTable not found in /usr/irissys/mgr/user/libfastlookup.so
USER>
[Using $ZF(-3) for Simple Library Function Calls](https://docs.intersystems.com/iris20251/csp/docbook/Doc.View.cls?KEY=BGCL_dynamic#BGCL_dynamic_loadone)

**Comment by kunal0297** [comment]
done made many changes in the files and specially fastlookup.c
 it should work now finger crossed

**Comment by r-cemper** [comment]
More problems:
#1) -------------------------------------
#12 10.28 IF sc '= 0 {
#12 10.28              ^
#12 10.28 <SYNTAX>
#12 10.28 USER>
--------------------------------------
iris.script is input to a terminal prompt. >> So. no {} , no multi-line blocks!
--- working version
ZN "USER"

; Load the shared library
SET sc=$ZF(-3, "/usr/lib/libfastlookup.so")
IF sc '= 0 WRITE "ERROR loading shared library",! HALT
WRITE "Shared library loaded successfully",!

; Compile ObjectScript classes
Do $System.OBJ.Load("/irisdev/app/PrefixTrie/Lookup.cls", "ck")
Do $System.OBJ.Load("/irisdev/app/test/test.trie.cls", "ck")

; Run test class
Do ##class(test.trie).Run()

Halt

**Comment by r-cemper** [comment]
More problems
#2) -------------------------------------------
QUIT $$$ERROR fails.  
this macro doesn't exist. Compilation fails!
simply return  QUIT '$$$OK   or any similar return code.
I wonder how you could compile this during testing.

**Comment by r-cemper** [comment]
#3) $ZF(-3) still not working.
------------------------------------------
I ran you code interactive:
USER>k ^PrefixTrieLibLoaded
USER>Set sc = $ZF(-3, "/usr/lib/libfastlookup.so")
USER>Set sc = $ZF(-3, "insert", value)
SET sc = $ZF(-3, "insert", value)
^
\<DYNAMIC LIBRARY LOAD\> */usr/irissys/mgr/user/insert: cannot open shared object file: No such file or directory 
-------------------------------------------------------
USER>Set sc = $ZF(-3, "")  ; clear dll
USER>Set sc = $ZF(-3, "/usr/lib/libfastlookup.so")  ; attach dll
USER>Set sc = $ZF(-3, "", "insert", value)  ; as by official documentation
SET sc = $ZF(-3, "", "insert", value)
^
\<INVALID ARGUMENT>
 -------------------------------------------------------
USER>; other variant in documentation
USER>Set sc = $ZF(-3, "")  ; clear dll
USER>Set sc = $ZF(-3, "/usr/lib/libfastlookup.so", "insert", value)  ; explicit DLL
SET sc = $ZF(-3, "/usr/lib/libfastlookup.so", "insert", value)  ; explicit DLL
^
\<INVALID ARGUMENT>
-------------------------------------------
Did this ever work in IRIS community on docker ? Which version ?
I have more the impression this is a port from Caché

You may check with some experts on $ZF(-3) in the community or with WRC

**Comment by kunal0297** [comment]
You're absolutely right — the $ZF(-3) behavior you're seeing (<DYNAMIC LIBRARY LOAD>, <INVALID ARGUMENT>, etc.) likely stems from restrictions in the IRIS Community Edition, especially when run via Docker. In some builds, $ZF(-3) is partially or completely restricted due to security or architecture reasons.

This project was originally developed with IRIS environments where $ZF(-3) worked without these constraints, and yes — it's very possible that some of it stems from legacy Caché logic.

That said, I’ve spent the day updating and modifying the project to improve compatibility and clean up some rough edges — so make sure you're working off the latest main branch. I’ll also work on improving the docs to clarify supported IRIS versions and environments.

Appreciate your feedback and patience
Thanks
